# com.example.app
BIDON_API_KEY = XXX
demoApplicationId = com.example.app

# Google MobileAds Credential
MOBILE_ADS_APPLICATION_ID = "ca-app-pub-YYYYYYYYYYYYYYYYY~XXXXXXXXXXX"

# App Release Signing Keys
storeSigningFileName = ""
storeSigningKey = XXX
signingKeyAlias = XXX
signingKeyPassword = XXX