name: Android CI

on: [push,workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: create local.properties
        run: touch local.properties

      - name: create keystore.properties
        run: touch keystore.properties

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: set Secrets Admob MOBILE_ADS_APPLICATION_ID
        env:
          MOBILE_ADS_APPLICATION_ID: ${{ secrets.MOBILE_ADS_APPLICATION_ID }}
        run:
          echo MOBILE_ADS_APPLICATION_ID=\"$ca-app-pub-XXXXXXXXXXXXXXXX~XXXXXXXXXX\" > ./keystore.properties

      - name: set Secrets BIDON_API_KEY
        env:
          BIDON_API_KEY: ${{ secrets.BIDON_API_KEY }}
        run:
          echo BIDON_API_KEY=\"$BIDON_API_KEY\" > ./keystore.properties

      - name: set Secrets DEMO_APPLICATION_ID
        env:
          demoApplicationId: ${{ secrets.DEMO_APPLICATION_ID }}
        run:
          echo DEMO_APPLICATION_ID=\"$com.example\" > ./keystore.properties

      # Execute unit tests
#      - name: KtLint check
#        run: ./gradlew ktLintCheck

      # Execute unit tests
      - name: Unit Test
        run: ./gradlew testProductionDebugUnitTest

